-- =============================================================================
-- supabase_update_coordinates.sql
-- Generated by scripts/generate_coord_updates.py
-- Sets latitude, longitude, city (clean), country (clean) for all 141 projects
-- Source coordinates: user-verified (116 unique city/country pairs)
-- =============================================================================

-- Run in the Supabase SQL Editor after supabase_import_projects.sql.
-- Idempotent — safe to re-run.

-- Row 1: EFP1  (Bavianskloof Valley, South Africa)
UPDATE projects
    SET latitude  = -33.68027,
        longitude = 24.51481,
        city      = 'Bavianskloof Valley',
        country   = 'South Africa'
    WHERE external_code = 'EFP1';

-- Row 2: IFF35  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'IFF35';

-- Row 3: IFF61  (Karachi, Pakistan)
UPDATE projects
    SET latitude  = 24.891,
        longitude = 67.0465,
        city      = 'Karachi',
        country   = 'Pakistan'
    WHERE external_code = 'IFF61';

-- Row 4: LDP15  (Dali, China)
UPDATE projects
    SET latitude  = 25.6065,
        longitude = 100.2676,
        city      = 'Dali',
        country   = 'China'
    WHERE external_code = 'LDP15';

-- Row 5: LDP3  (Leh, India)
UPDATE projects
    SET latitude  = 34.160889,
        longitude = 77.581696,
        city      = 'Leh',
        country   = 'India'
    WHERE external_code = 'LDP3';

-- Row 6: LDP71  (Sobral, Brazil)
UPDATE projects
    SET latitude  = -3.670293,
        longitude = -40.314005,
        city      = 'Sobral',
        country   = 'Brazil'
    WHERE external_code = 'LDP71';

-- Row 7: IFF15  (Porto Alegre, Brazil)
UPDATE projects
    SET latitude  = -30.029726,
        longitude = -51.229265,
        city      = 'Porto Alegre',
        country   = 'Brazil'
    WHERE external_code = 'IFF15';

-- Row 8: IFF4  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'IFF4';

-- Row 9: IFF44  (Karachi, Pakistan)
UPDATE projects
    SET latitude  = 24.89114,
        longitude = 67.04658,
        city      = 'Karachi',
        country   = 'Pakistan'
    WHERE external_code = 'IFF44';

-- Row 10: IFF59  (Cairo, Egypt)
UPDATE projects
    SET latitude  = 30.046784,
        longitude = 31.239582,
        city      = 'Cairo',
        country   = 'Egypt'
    WHERE external_code = 'IFF59';

-- Row 11: LDP25  (Karamoja, Uganda)
UPDATE projects
    SET latitude  = 2.75,
        longitude = 34.25,
        city      = 'Karamoja',
        country   = 'Uganda'
    WHERE external_code = 'LDP25';

-- Row 12: LDP52  (Chengdu, China)
UPDATE projects
    SET latitude  = 30.6599,
        longitude = 104.0634,
        city      = 'Chengdu',
        country   = 'China'
    WHERE external_code = 'LDP52';

-- Row 13: IFF12  (Concepción, Chile)
UPDATE projects
    SET latitude  = -36.827393,
        longitude = -73.05037,
        city      = 'Concepción',
        country   = 'Chile'
    WHERE external_code = 'IFF12';

-- Row 14: LDP1  (Munich, Germany)
UPDATE projects
    SET latitude  = 48.14156,
        longitude = 11.567313,
        city      = 'Munich',
        country   = 'Germany'
    WHERE external_code = 'LDP1';

-- Row 15: LDP12  (Changyuan, China)
UPDATE projects
    SET latitude  = 35.2125,
        longitude = 114.735,
        city      = 'Changyuan',
        country   = 'China'
    WHERE external_code = 'LDP12';

-- Row 16: LDP21  (Shangcun Village, China)
UPDATE projects
    SET latitude  = 29.945833,
        longitude = 118.748056,
        city      = 'Shangcun Village',
        country   = 'China'
    WHERE external_code = 'LDP21';

-- Row 17: LDP28  (Alibaug, India)
UPDATE projects
    SET latitude  = 18.640548,
        longitude = 72.872215,
        city      = 'Alibaug',
        country   = 'India'
    WHERE external_code = 'LDP28';

-- Row 18: LDP43  (Chongli, China)
UPDATE projects
    SET latitude  = 40.998857,
        longitude = 115.261397,
        city      = 'Chongli',
        country   = 'China'
    WHERE external_code = 'LDP43';

-- Row 19: IFF24  (Bengaluru, India)
UPDATE projects
    SET latitude  = 12.97422,
        longitude = 77.593185,
        city      = 'Bengaluru',
        country   = 'India'
    WHERE external_code = 'IFF24';

-- Row 20: IFF37  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'IFF37';

-- Row 21: LDP17  (Pune, India)
UPDATE projects
    SET latitude  = 18.518909,
        longitude = 73.856116,
        city      = 'Pune',
        country   = 'India'
    WHERE external_code = 'LDP17';

-- Row 22: LDP20  (Pune, India)
UPDATE projects
    SET latitude  = 18.518909,
        longitude = 73.856116,
        city      = 'Pune',
        country   = 'India'
    WHERE external_code = 'LDP20';

-- Row 23: LDP23  (Wakiso, Uganda)
UPDATE projects
    SET latitude  = 0.40444,
        longitude = 32.45944,
        city      = 'Wakiso',
        country   = 'Uganda'
    WHERE external_code = 'LDP23';

-- Row 24: LDP67  (Hanoi, Vietnam)
UPDATE projects
    SET latitude  = 21.031477,
        longitude = 105.844719,
        city      = 'Hanoi',
        country   = 'Vietnam'
    WHERE external_code = 'LDP67';

-- Row 25: IFF3  (Manhumirim, Brazil)
UPDATE projects
    SET latitude  = -20.358367,
        longitude = -41.95892,
        city      = 'Manhumirim',
        country   = 'Brazil'
    WHERE external_code = 'IFF3';

-- Row 26: IFF7  (Southwest China, China)
UPDATE projects
    SET latitude  = 26.0,
        longitude = 104.0,
        city      = 'Southwest China',
        country   = 'China'
    WHERE external_code = 'IFF7';

-- Row 27: LDP11  (Reci, Romania)
UPDATE projects
    SET latitude  = 45.85,
        longitude = 25.933,
        city      = 'Reci',
        country   = 'Romania'
    WHERE external_code = 'LDP11';

-- Row 28: LDP59  (Khurrianwala, Pakistan)
UPDATE projects
    SET latitude  = 31.51722,
        longitude = 73.26667,
        city      = 'Khurrianwala',
        country   = 'Pakistan'
    WHERE external_code = 'LDP59';

-- Row 29: LDP6  (Kunming, China)
UPDATE projects
    SET latitude  = 25.03926,
        longitude = 102.718887,
        city      = 'Kunming',
        country   = 'China'
    WHERE external_code = 'LDP6';

-- Row 30: LDP72  (Kuakata, Bangladesh)
UPDATE projects
    SET latitude  = 21.815347,
        longitude = 90.140874,
        city      = 'Kuakata',
        country   = 'Bangladesh'
    WHERE external_code = 'LDP72';

-- Row 31: IFF2  (Rio de Janeiro, Brazil)
UPDATE projects
    SET latitude  = -22.902094,
        longitude = -43.128199,
        city      = 'Rio de Janeiro',
        country   = 'Brazil'
    WHERE external_code = 'IFF2';

-- Row 32: LDP2  (Ipoh, Malaysia)
UPDATE projects
    SET latitude  = 4.59342,
        longitude = 101.087676,
        city      = 'Ipoh',
        country   = 'Malaysia'
    WHERE external_code = 'LDP2';

-- Row 33: LDP31  (Yixing, China)
UPDATE projects
    SET latitude  = 31.36,
        longitude = 119.815,
        city      = 'Yixing',
        country   = 'China'
    WHERE external_code = 'LDP31';

-- Row 34: LDP37  (Canoas, Brazil)
UPDATE projects
    SET latitude  = -29.920059,
        longitude = -51.179004,
        city      = 'Canoas',
        country   = 'Brazil'
    WHERE external_code = 'LDP37';

-- Row 35: LDP61  (Valinhos, Brazil)
UPDATE projects
    SET latitude  = -22.970559,
        longitude = -46.995831,
        city      = 'Valinhos',
        country   = 'Brazil'
    WHERE external_code = 'LDP61';

-- Row 36: LDP73  (Sobral, Brazil)
UPDATE projects
    SET latitude  = -3.670293,
        longitude = -40.314005,
        city      = 'Sobral',
        country   = 'Brazil'
    WHERE external_code = 'LDP73';

-- Row 37: IFF34  (Guadalajara, Mexico)
UPDATE projects
    SET latitude  = 20.662066,
        longitude = -103.363739,
        city      = 'Guadalajara',
        country   = 'Mexico'
    WHERE external_code = 'IFF34';

-- Row 38: LDP18  (Beijing, China)
UPDATE projects
    SET latitude  = 39.912433,
        longitude = 116.401033,
        city      = 'Beijing',
        country   = 'China'
    WHERE external_code = 'LDP18';

-- Row 39: LDP19  (Yueyang, China)
UPDATE projects
    SET latitude  = 29.1446,
        longitude = 113.1161,
        city      = 'Yueyang',
        country   = 'China'
    WHERE external_code = 'LDP19';

-- Row 40: LDP22  (Gaobeidian, China)
UPDATE projects
    SET latitude  = 39.28486,
        longitude = 115.954605,
        city      = 'Gaobeidian',
        country   = 'China'
    WHERE external_code = 'LDP22';

-- Row 41: LDP62  (Guian New Area, China)
UPDATE projects
    SET latitude  = 26.4688,
        longitude = 106.4831,
        city      = 'Guian New Area',
        country   = 'China'
    WHERE external_code = 'LDP62';

-- Row 42: LDP8  (Vienna, Austria)
UPDATE projects
    SET latitude  = 48.182288,
        longitude = 16.075958,
        city      = 'Vienna',
        country   = 'Austria'
    WHERE external_code = 'LDP8';

-- Row 43: IFF48  (New Cairo, Egypt)
UPDATE projects
    SET latitude  = 30.030885,
        longitude = 31.421844,
        city      = 'New Cairo',
        country   = 'Egypt'
    WHERE external_code = 'IFF48';

-- Row 44: LDP24  (São Luís, Brazil)
UPDATE projects
    SET latitude  = -2.529973,
        longitude = -44.300193,
        city      = 'São Luís',
        country   = 'Brazil'
    WHERE external_code = 'LDP24';

-- Row 45: LDP27  (Fujian, China)
UPDATE projects
    SET latitude  = 26.484,
        longitude = 117.925,
        city      = 'Fujian',
        country   = 'China'
    WHERE external_code = 'LDP27';

-- Row 46: LDP45  (Bengaluru, India)
UPDATE projects
    SET latitude  = 12.97422,
        longitude = 77.593185,
        city      = 'Bengaluru',
        country   = 'India'
    WHERE external_code = 'LDP45';

-- Row 47: LDP70  (Zaghouan, Tunisia)
UPDATE projects
    SET latitude  = 36.404973,
        longitude = 10.142706,
        city      = 'Zaghouan',
        country   = 'Tunisia'
    WHERE external_code = 'LDP70';

-- Row 48: IFF16  (Juriti, Brazil)
UPDATE projects
    SET latitude  = -2.1528,
        longitude = -56.090733,
        city      = 'Juriti',
        country   = 'Brazil'
    WHERE external_code = 'IFF16';

-- Row 49: IFF42  (Pisa, Italy)
UPDATE projects
    SET latitude  = 43.718811,
        longitude = 10.398847,
        city      = 'Pisa',
        country   = 'Italy'
    WHERE external_code = 'IFF42';

-- Row 50: LDP14  (Dubai, United Arab Emirates)
UPDATE projects
    SET latitude  = 25.270678,
        longitude = 55.299413,
        city      = 'Dubai',
        country   = 'United Arab Emirates'
    WHERE external_code = 'LDP14';

-- Row 51: LDP30  (Bhubaneswar, India)
UPDATE projects
    SET latitude  = 20.296059,
        longitude = 85.824539,
        city      = 'Bhubaneswar',
        country   = 'India'
    WHERE external_code = 'LDP30';

-- Row 52: LDP55  (Baoxi, China)
UPDATE projects
    SET latitude  = 28.00611,
        longitude = 118.76028,
        city      = 'Baoxi',
        country   = 'China'
    WHERE external_code = 'LDP55';

-- Row 53: LDP65  (São Paulo/Diadema, Brazil)
UPDATE projects
    SET latitude  = -23.6865,
        longitude = -46.6234,
        city      = 'São Paulo/Diadema',
        country   = 'Brazil'
    WHERE external_code = 'LDP65';

-- Row 54: IFF17  (Foz do Iguaçu, Brazil)
UPDATE projects
    SET latitude  = -25.538124,
        longitude = -54.585437,
        city      = 'Foz do Iguaçu',
        country   = 'Brazil'
    WHERE external_code = 'IFF17';

-- Row 55: IFF52  (Karachi, Pakistan)
UPDATE projects
    SET latitude  = 24.89114,
        longitude = 67.04658,
        city      = 'Karachi',
        country   = 'Pakistan'
    WHERE external_code = 'IFF52';

-- Row 56: IFF56  (Jacobabad, Pakistan)
UPDATE projects
    SET latitude  = 28.2793,
        longitude = 68.43727,
        city      = 'Jacobabad',
        country   = 'Pakistan'
    WHERE external_code = 'IFF56';

-- Row 57: LDP44  (Bengaluru, India)
UPDATE projects
    SET latitude  = 12.97422,
        longitude = 77.593185,
        city      = 'Bengaluru',
        country   = 'India'
    WHERE external_code = 'LDP44';

-- Row 58: LDP50  (Prilep, North Macedonia)
UPDATE projects
    SET latitude  = 41.347,
        longitude = 21.55695,
        city      = 'Prilep',
        country   = 'North Macedonia'
    WHERE external_code = 'LDP50';

-- Row 59: LDP54  (Beijing, China)
UPDATE projects
    SET latitude  = 39.912433,
        longitude = 116.401033,
        city      = 'Beijing',
        country   = 'China'
    WHERE external_code = 'LDP54';

-- Row 60: IFF5  (Cairo, Egypt)
UPDATE projects
    SET latitude  = 30.046784,
        longitude = 31.239582,
        city      = 'Cairo',
        country   = 'Egypt'
    WHERE external_code = 'IFF5';

-- Row 61: IFF55  (Boa Vista, Brazil)
UPDATE projects
    SET latitude  = 2.820337,
        longitude = -60.671799,
        city      = 'Boa Vista',
        country   = 'Brazil'
    WHERE external_code = 'IFF55';

-- Row 62: IFF9  (Plosca, Romania)
UPDATE projects
    SET latitude  = 44.033,
        longitude = 25.117,
        city      = 'Plosca',
        country   = 'Romania'
    WHERE external_code = 'IFF9';

-- Row 63: LDP35  (Beijing, China)
UPDATE projects
    SET latitude  = 39.912433,
        longitude = 116.401033,
        city      = 'Beijing',
        country   = 'China'
    WHERE external_code = 'LDP35';

-- Row 64: LDP47  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'LDP47';

-- Row 65: LDP7  (Fengning, China)
UPDATE projects
    SET latitude  = 41.2,
        longitude = 116.65,
        city      = 'Fengning',
        country   = 'China'
    WHERE external_code = 'LDP7';

-- Row 66: LDP16  (Wuzhen, China)
UPDATE projects
    SET latitude  = 30.742453,
        longitude = 120.488833,
        city      = 'Wuzhen',
        country   = 'China'
    WHERE external_code = 'LDP16';

-- Row 67: LDP29  (Bisceglie, Italy)
UPDATE projects
    SET latitude  = 41.229019,
        longitude = 16.495083,
        city      = 'Bisceglie',
        country   = 'Italy'
    WHERE external_code = 'LDP29';

-- Row 68: LDP32  (Copenhagen, Denmark)
UPDATE projects
    SET latitude  = 55.679521,
        longitude = 12.567034,
        city      = 'Copenhagen',
        country   = 'Denmark'
    WHERE external_code = 'LDP32';

-- Row 69: LDP53  (Kusatsu, Japan)
UPDATE projects
    SET latitude  = 35.01748,
        longitude = 135.955594,
        city      = 'Kusatsu',
        country   = 'Japan'
    WHERE external_code = 'LDP53';

-- Row 70: LDP66  (Milan, Italy)
UPDATE projects
    SET latitude  = 45.464654,
        longitude = 9.188315,
        city      = 'Milan',
        country   = 'Italy'
    WHERE external_code = 'LDP66';

-- Row 71: LDP9  (Murstetten, Austria)
UPDATE projects
    SET latitude  = 48.2333,
        longitude = 15.8167,
        city      = 'Murstetten',
        country   = 'Austria'
    WHERE external_code = 'LDP9';

-- Row 72: IFF25  (Ulaanbaatar, Mongolia)
UPDATE projects
    SET latitude  = 47.898009,
        longitude = 106.910015,
        city      = 'Ulaanbaatar',
        country   = 'Mongolia'
    WHERE external_code = 'IFF25';

-- Row 73: IFF46  (Athabasca, Canada)
UPDATE projects
    SET latitude  = 54.716497,
        longitude = -113.284176,
        city      = 'Athabasca',
        country   = 'Canada'
    WHERE external_code = 'IFF46';

-- Row 74: IFF49  (Nazaré Paulista, Brazil)
UPDATE projects
    SET latitude  = -23.183331,
        longitude = -46.399813,
        city      = 'Nazaré Paulista',
        country   = 'Brazil'
    WHERE external_code = 'IFF49';

-- Row 75: LDP48  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'LDP48';

-- Row 76: LDP49  (Milan, Italy)
UPDATE projects
    SET latitude  = 45.464654,
        longitude = 9.188315,
        city      = 'Milan',
        country   = 'Italy'
    WHERE external_code = 'LDP49';

-- Row 77: LDP69  (Jhenaidah, Bangladesh)
UPDATE projects
    SET latitude  = 23.633841,
        longitude = 89.066856,
        city      = 'Jhenaidah',
        country   = 'Bangladesh'
    WHERE external_code = 'LDP69';

-- Row 78: IFF11  (Thessaloniki, Greece)
UPDATE projects
    SET latitude  = 40.63741,
        longitude = 22.94096,
        city      = 'Thessaloniki',
        country   = 'Greece'
    WHERE external_code = 'IFF11';

-- Row 79: IFF51  (Arequipa, Peru)
UPDATE projects
    SET latitude  = -16.397,
        longitude = -71.53748,
        city      = 'Arequipa',
        country   = 'Peru'
    WHERE external_code = 'IFF51';

-- Row 80: LDP13  (Nanjing, China)
UPDATE projects
    SET latitude  = 32.053418,
        longitude = 118.776849,
        city      = 'Nanjing',
        country   = 'China'
    WHERE external_code = 'LDP13';

-- Row 81: LDP26  (Beijing, China)
UPDATE projects
    SET latitude  = 39.910309,
        longitude = 116.365435,
        city      = 'Beijing',
        country   = 'China'
    WHERE external_code = 'LDP26';

-- Row 82: LDP41  (Nanjing, China)
UPDATE projects
    SET latitude  = 32.053418,
        longitude = 118.776849,
        city      = 'Nanjing',
        country   = 'China'
    WHERE external_code = 'LDP41';

-- Row 83: LDP60  (Gopalganj, Bangladesh)
UPDATE projects
    SET latitude  = 23.013014,
        longitude = 89.822405,
        city      = 'Gopalganj',
        country   = 'Bangladesh'
    WHERE external_code = 'LDP60';

-- Row 84: IFF10  (New York City, United States of America)
UPDATE projects
    SET latitude  = 40.71427,
        longitude = -74.00597,
        city      = 'New York City',
        country   = 'United States of America'
    WHERE external_code = 'IFF10';

-- Row 85: IFF14  (New Delhi, India)
UPDATE projects
    SET latitude  = 28.635773,
        longitude = 77.224433,
        city      = 'New Delhi',
        country   = 'India'
    WHERE external_code = 'IFF14';

-- Row 86: IFF45  (Maida, Italy)
UPDATE projects
    SET latitude  = 38.859613,
        longitude = 16.3637,
        city      = 'Maida',
        country   = 'Italy'
    WHERE external_code = 'IFF45';

-- Row 87: LDP34  (Burgos, Spain)
UPDATE projects
    SET latitude  = 42.34106,
        longitude = -3.70184,
        city      = 'Burgos',
        country   = 'Spain'
    WHERE external_code = 'LDP34';

-- Row 88: LDP36  (Burgos, Spain)
UPDATE projects
    SET latitude  = 42.34106,
        longitude = -3.70184,
        city      = 'Burgos',
        country   = 'Spain'
    WHERE external_code = 'LDP36';

-- Row 89: LDP38  (Montevideo, Uruguay)
UPDATE projects
    SET latitude  = -34.894443,
        longitude = -56.173933,
        city      = 'Montevideo',
        country   = 'Uruguay'
    WHERE external_code = 'LDP38';

-- Row 90: LDP39  (Uthal, Pakistan)
UPDATE projects
    SET latitude  = 25.8039,
        longitude = 66.61949,
        city      = 'Uthal',
        country   = 'Pakistan'
    WHERE external_code = 'LDP39';

-- Row 91: IFF43  (Sobral, Brazil)
UPDATE projects
    SET latitude  = -3.670293,
        longitude = -40.314005,
        city      = 'Sobral',
        country   = 'Brazil'
    WHERE external_code = 'IFF43';

-- Row 92: IFF58  (Uthal, Pakistan)
UPDATE projects
    SET latitude  = 25.804807,
        longitude = 66.62028,
        city      = 'Uthal',
        country   = 'Pakistan'
    WHERE external_code = 'IFF58';

-- Row 93: IFF62  (Benguerir, Morocco)
UPDATE projects
    SET latitude  = 32.240335,
        longitude = -7.953709,
        city      = 'Benguerir',
        country   = 'Morocco'
    WHERE external_code = 'IFF62';

-- Row 94: LDP58  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'LDP58';

-- Row 95: LDP63  (Milan, Italy)
UPDATE projects
    SET latitude  = 45.464654,
        longitude = 9.188315,
        city      = 'Milan',
        country   = 'Italy'
    WHERE external_code = 'LDP63';

-- Row 96: LDP68  (Hanoi, Vietnam)
UPDATE projects
    SET latitude  = 21.031477,
        longitude = 105.844719,
        city      = 'Hanoi',
        country   = 'Vietnam'
    WHERE external_code = 'LDP68';

-- Row 97: IFF39  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF39';

-- Row 98: EFP2  (Valladolid, Spain)
UPDATE projects
    SET latitude  = 41.65351,
        longitude = -4.72378,
        city      = 'Valladolid',
        country   = 'Spain'
    WHERE external_code = 'EFP2';

-- Row 99: IFF1  (Irbid, Jordan)
UPDATE projects
    SET latitude  = 32.554655,
        longitude = 35.849792,
        city      = 'Irbid',
        country   = 'Jordan'
    WHERE external_code = 'IFF1';

-- Row 100: IFF13  (Logroño, Spain)
UPDATE projects
    SET latitude  = 42.46411,
        longitude = -2.44852,
        city      = 'Logroño',
        country   = 'Spain'
    WHERE external_code = 'IFF13';

-- Row 101: IFF18  (Sal Island, Cape Verde)
UPDATE projects
    SET latitude  = 16.775533,
        longitude = -22.921133,
        city      = 'Sal Island',
        country   = 'Cape Verde'
    WHERE external_code = 'IFF18';

-- Row 102: IFF19  (São Nicolau, Cape Verde)
UPDATE projects
    SET latitude  = 16.835,
        longitude = -24.8076,
        city      = 'São Nicolau',
        country   = 'Cape Verde'
    WHERE external_code = 'IFF19';

-- Row 103: IFF20  (Brava & Fogo Islands, Cape Verde)
UPDATE projects
    SET latitude  = 14.896567,
        longitude = -24.5415,
        city      = 'Brava & Fogo Islands',
        country   = 'Cape Verde'
    WHERE external_code = 'IFF20';

-- Row 104: IFF21  (Belo Horizonte, Brazil)
UPDATE projects
    SET latitude  = -19.918219,
        longitude = -43.938831,
        city      = 'Belo Horizonte',
        country   = 'Brazil'
    WHERE external_code = 'IFF21';

-- Row 105: IFF22  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF22';

-- Row 106: IFF23  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF23';

-- Row 107: IFF26  (Natal, Brazil)
UPDATE projects
    SET latitude  = -5.800832,
        longitude = -35.225822,
        city      = 'Natal',
        country   = 'Brazil'
    WHERE external_code = 'IFF26';

-- Row 108: IFF27  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF27';

-- Row 109: IFF28  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF28';

-- Row 110: IFF29  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF29';

-- Row 111: IFF30  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF30';

-- Row 112: IFF31  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF31';

-- Row 113: IFF32  (Montevideo, Uruguay)
UPDATE projects
    SET latitude  = -34.894443,
        longitude = -56.173933,
        city      = 'Montevideo',
        country   = 'Uruguay'
    WHERE external_code = 'IFF32';

-- Row 114: IFF33  (Hong Kong, China)
UPDATE projects
    SET latitude  = 22.296807,
        longitude = 114.161627,
        city      = 'Hong Kong',
        country   = 'China'
    WHERE external_code = 'IFF33';

-- Row 115: IFF36  (Calgary, Canada)
UPDATE projects
    SET latitude  = 51.048735,
        longitude = -114.072474,
        city      = 'Calgary',
        country   = 'Canada'
    WHERE external_code = 'IFF36';

-- Row 116: IFF38  (Bengaluru, India)
UPDATE projects
    SET latitude  = 12.97422,
        longitude = 77.593185,
        city      = 'Bengaluru',
        country   = 'India'
    WHERE external_code = 'IFF38';

-- Row 117: IFF40  (Shanghai, China)
UPDATE projects
    SET latitude  = 31.222934,
        longitude = 121.461763,
        city      = 'Shanghai',
        country   = 'China'
    WHERE external_code = 'IFF40';

-- Row 118: IFF41  (Sobral, Brazil)
UPDATE projects
    SET latitude  = -3.670293,
        longitude = -40.314005,
        city      = 'Sobral',
        country   = 'Brazil'
    WHERE external_code = 'IFF41';

-- Row 119: IFF47  (Dhaka, Bangladesh)
UPDATE projects
    SET latitude  = 23.766169,
        longitude = 90.390771,
        city      = 'Dhaka',
        country   = 'Bangladesh'
    WHERE external_code = 'IFF47';

-- Row 120: IFF50  (Heraklion, Greece)
UPDATE projects
    SET latitude  = 35.339887,
        longitude = 25.141917,
        city      = 'Heraklion',
        country   = 'Greece'
    WHERE external_code = 'IFF50';

-- Row 121: IFF53  (Bogotá, Colombia)
UPDATE projects
    SET latitude  = 4.673345,
        longitude = -74.073339,
        city      = 'Bogotá',
        country   = 'Colombia'
    WHERE external_code = 'IFF53';

-- Row 122: IFF54  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'IFF54';

-- Row 123: IFF57  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'IFF57';

-- SKIP IFF6: no geocodable location ('Everywhere', 'Unknown')
-- Row 125: IFF60  (Karachi, Pakistan)
UPDATE projects
    SET latitude  = 24.89114,
        longitude = 67.04658,
        city      = 'Karachi',
        country   = 'Pakistan'
    WHERE external_code = 'IFF60';

-- Row 126: IFF63  (Sobral, Brazil)
UPDATE projects
    SET latitude  = -3.670293,
        longitude = -40.314005,
        city      = 'Sobral',
        country   = 'Brazil'
    WHERE external_code = 'IFF63';

-- Row 127: IFF64  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'IFF64';

-- Row 128: IFF8  (Turin, Italy)
UPDATE projects
    SET latitude  = 45.085719,
        longitude = 7.705418,
        city      = 'Turin',
        country   = 'Italy'
    WHERE external_code = 'IFF8';

-- Row 129: LDP10  (Bucharest, Romania)
UPDATE projects
    SET latitude  = 44.43268,
        longitude = 26.10201,
        city      = 'Bucharest',
        country   = 'Romania'
    WHERE external_code = 'LDP10';

-- Row 130: LDP33  (Valladolid, Spain)
UPDATE projects
    SET latitude  = 41.653293,
        longitude = -4.724193,
        city      = 'Valladolid',
        country   = 'Spain'
    WHERE external_code = 'LDP33';

-- Row 131: LDP4  (Fayoum, Egypt)
UPDATE projects
    SET latitude  = 29.311889,
        longitude = 30.8268,
        city      = 'Fayoum',
        country   = 'Egypt'
    WHERE external_code = 'LDP4';

-- Row 132: LDP40  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'LDP40';

-- Row 133: LDP42  (Zhuhai, China)
UPDATE projects
    SET latitude  = 22.274046,
        longitude = 113.57223,
        city      = 'Zhuhai',
        country   = 'China'
    WHERE external_code = 'LDP42';

-- Row 134: LDP46  (Pamplona, Spain)
UPDATE projects
    SET latitude  = 42.81687,
        longitude = -1.64323,
        city      = 'Pamplona',
        country   = 'Spain'
    WHERE external_code = 'LDP46';

-- Row 135: LDP5  (Karachi, Pakistan)
UPDATE projects
    SET latitude  = 24.89114,
        longitude = 67.04658,
        city      = 'Karachi',
        country   = 'Pakistan'
    WHERE external_code = 'LDP5';

-- Row 136: LDP51  (São Paulo, Brazil)
UPDATE projects
    SET latitude  = -23.543931,
        longitude = -46.631567,
        city      = 'São Paulo',
        country   = 'Brazil'
    WHERE external_code = 'LDP51';

-- Row 137: LDP56  (Yanqing, China)
UPDATE projects
    SET latitude  = 40.42,
        longitude = 116.083336,
        city      = 'Yanqing',
        country   = 'China'
    WHERE external_code = 'LDP56';

-- Row 138: LDP57  (Pamplona, Spain)
UPDATE projects
    SET latitude  = 42.81687,
        longitude = -1.64323,
        city      = 'Pamplona',
        country   = 'Spain'
    WHERE external_code = 'LDP57';

-- Row 139: LDP64  (Zhuhai, China)
UPDATE projects
    SET latitude  = 22.274046,
        longitude = 113.57223,
        city      = 'Zhuhai',
        country   = 'China'
    WHERE external_code = 'LDP64';

-- Row 140: LDP74  (São Luís, Brazil)
UPDATE projects
    SET latitude  = -2.529973,
        longitude = -44.300193,
        city      = 'São Luís',
        country   = 'Brazil'
    WHERE external_code = 'LDP74';

-- Row 141: LDP75  (Chengmai, China)
UPDATE projects
    SET latitude  = 19.7385,
        longitude = 110.006767,
        city      = 'Chengmai',
        country   = 'China'
    WHERE external_code = 'LDP75';

-- =============================================================================
-- Verification (run after applying this script):
-- =============================================================================
-- Total UPDATEs generated : 140
-- Skipped (no location)   : 1
-- Missing from map        : 0
--
-- SELECT COUNT(*) FROM projects WHERE latitude IS NOT NULL;   -- expect ~139
-- SELECT COUNT(*) FROM projects WHERE latitude IS NULL;        -- expect ~2
-- SELECT external_code, city, country, latitude, longitude
--   FROM projects WHERE external_code IN ('EFP1','LDP14','LDP67','IFF53');
-- SELECT country, COUNT(*) FROM projects
--   WHERE external_code IS NOT NULL
--   GROUP BY country ORDER BY COUNT(*) DESC;
