"""
Migrate 2026 guidebook images from source folders into frontend/public/project_images/
and generate SQL to insert project_images records.

Usage:
  # Step 1: Copy files and generate SQL (run on host)
  python backend/scripts/migrate_2026_images.py

  # Step 2: Apply SQL to Docker DB
  docker exec -i atlas_33-db-1 psql -U postgres -d panorama_sdg < data/sql/insert_2026_images.sql
"""
import sys
import os
import re
import shutil

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))

SOURCE_BASE = os.path.join(PROJECT_ROOT, "PROJETO_AGENDA_UIA_2026")
ARCHIVES = [
    "_UIA-20260410T210012Z-3-001/_UIA",
    "_UIA-20260410T210012Z-3-002/_UIA",
    "_UIA-20260410T210012Z-3-003/_UIA",
]
GROUP_NAMES = ["GROUP#1 IMAGES", "GROUP#2 IMAGES", "GROUP#3 IMAGES"]

DEST_DIR = os.path.join(PROJECT_ROOT, "frontend", "public", "project_images")
SQL_OUT = os.path.join(PROJECT_ROOT, "data", "sql", "insert_2026_images.sql")

ALLOWED_EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif"}


def collect_source_folders():
    """Return dict: project_code -> list of source image folders."""
    all_folders: dict[str, list[str]] = {}
    for archive in ARCHIVES:
        for group in GROUP_NAMES:
            group_dir = os.path.join(SOURCE_BASE, archive, group)
            if not os.path.isdir(group_dir):
                continue
            for entry in sorted(os.listdir(group_dir)):
                entry_path = os.path.join(group_dir, entry)
                if not os.path.isdir(entry_path):
                    continue
                m = re.match(r"^(P\d+)_", entry)
                if not m:
                    print(f"  [SKIP] Unrecognised folder: {entry}")
                    continue
                code = m.group(1)
                all_folders.setdefault(code, []).append(entry_path)
    return all_folders


def migrate():
    os.makedirs(DEST_DIR, exist_ok=True)
    os.makedirs(os.path.dirname(SQL_OUT), exist_ok=True)

    all_folders = collect_source_folders()
    print(f"[INFO] Found {len(all_folders)} unique project codes with images.")

    total_copied = 0
    sql_lines = [
        "-- Auto-generated by migrate_2026_images.py",
        "-- Inserts project_images records for 2026 guidebook projects.",
        "-- Apply: docker exec -i atlas_33-db-1 psql -U postgres -d panorama_sdg < data/sql/insert_2026_images.sql",
        "",
        "BEGIN;",
        "",
    ]

    for code, src_folders in sorted(all_folders.items()):
        image_files = []
        for src_folder in src_folders:
            for fname in sorted(os.listdir(src_folder)):
                ext = os.path.splitext(fname)[1].lower()
                if ext not in ALLOWED_EXT:
                    continue
                image_files.append(os.path.join(src_folder, fname))

        if not image_files:
            print(f"  [WARN] {code}: no image files found")
            continue

        display_order = 0
        dest_names = []
        for src_path in image_files:
            orig_name = os.path.basename(src_path)
            clean_name = re.sub(r"[^\w.\-]", "-", orig_name.strip("_").strip())
            dest_name = f"{code}_{clean_name}"
            dest_path = os.path.join(DEST_DIR, dest_name)

            if not os.path.exists(dest_path):
                shutil.copy2(src_path, dest_path)
                total_copied += 1

            dest_names.append((dest_name, display_order))
            display_order += 1

        # Generate SQL using a subquery to get the project UUID
        sql_lines.append(f"-- {code}: {len(dest_names)} image(s)")
        sql_lines.append(f"DO $$ DECLARE pid UUID; BEGIN")
        sql_lines.append(
            f"  SELECT id INTO pid FROM projects WHERE external_code = '{code}' LIMIT 1;"
        )
        sql_lines.append(f"  IF pid IS NOT NULL THEN")
        for dest_name, order in dest_names:
            url = f"/project_images/{dest_name}"
            sql_lines.append(
                f"    INSERT INTO project_images (id, project_id, image_url, display_order)"
                f" VALUES (gen_random_uuid(), pid, '{url}', {order})"
                f" ON CONFLICT DO NOTHING;"
            )
        sql_lines.append(f"  END IF;")
        sql_lines.append(f"END $$;")
        sql_lines.append("")
        print(f"  [OK] {code}: {len(dest_names)} image(s)")

    sql_lines.append("COMMIT;")

    with open(SQL_OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\n[DONE] Copied {total_copied} files.")
    print(f"[SQL]  Generated {SQL_OUT}")
    print(f"\nNow run:")
    print(f"  docker exec -i atlas_33-db-1 psql -U postgres -d panorama_sdg < data/sql/insert_2026_images.sql")


if __name__ == "__main__":
    migrate()
