#!/usr/bin/env python3
"""
excel_to_guidebook_sql.py
Reads FINAL SELECTION.xlsx and generates supabase_import_guidebook_2026.sql
"""

import os, sys, uuid
from pathlib import Path

try:
    import openpyxl
except ImportError:
    print("ERROR: pip install openpyxl"); sys.exit(1)

REPO_ROOT  = Path(__file__).parent.parent
EXCEL_FILE = Path(r"A:\Projeto_Cid_UIA\Nova pasta\PROJETO_AGENDA_UIA\_UIA-20260410T210012Z-3-002\_UIA\ANSWERS\FINAL SELECTION.xlsx")
if os.environ.get("EXCEL_FILE"):
    EXCEL_FILE = Path(os.environ["EXCEL_FILE"])
OUTPUT_SQL = REPO_ROOT / "data" / "sql" / "supabase_import_2026.sql"

STATUS_MAP = {
    "completed": "IMPLEMENTED", "completed/built": "IMPLEMENTED", "built": "IMPLEMENTED",
    "design phase": "PLANNED",  "planning": "PLANNED",
    "under construction": "IN_PROGRESS", "in progress": "IN_PROGRESS",
}

def esc(value, max_len=0):
    if value is None or str(value).strip() in ("", "nan", "None"):
        return "NULL"
    s = str(value).strip().replace("\xa0", " ").replace("\r", "").replace("\n", " ")
    if max_len > 0:
        s = s[:max_len]
    return "'" + s.replace("'", "''") + "'"

# Corrected UIA Mapping:
# Official UIA 1 (Europe) -> SECTION_I
# Official UIA 2 (Eastern Europe/ME) -> SECTION_II or SECTION_III
# Official UIA 3 (Americas) -> SECTION_V
# Official UIA 4 (Asia/Oceania) -> SECTION_IV
# Official UIA 5 (Africa) -> SECTION_III
def map_region(val, country=""):
    if not val:
        return "'SECTION_I'"
    v = str(val).strip().lower()
    
    if "v" in v or "5" in v:
        return "'SECTION_III'" # Africa -> Section III (Middle East & Africa)
    if "iv" in v or "4" in v:
        return "'SECTION_IV'" # Asia & Pacific
    if "iii" in v or "3" in v:
        return "'SECTION_V'"   # Americas -> Section V
    if "ii" in v or "2" in v:
        # Middle East countries often tagged as Region 2 in source
        me_keywords = ["uae", "united arab emirates", "egypt", "jordan", "lebanon", "saudi", "qatar", "dubai"]
        if country and any(k in str(country).lower() for k in me_keywords):
            return "'SECTION_III'"
        return "'SECTION_II'"
    return "'SECTION_I'"

def map_status(val):
    if not val:
        return "PLANNED"
    return STATUS_MAP.get(str(val).strip().lower(), "PLANNED")

if not EXCEL_FILE.exists():
    print(f"ERROR: Not found:\n  {EXCEL_FILE}"); sys.exit(1)

print(f"Loading: {EXCEL_FILE}")
wb = openpyxl.load_workbook(EXCEL_FILE, data_only=True)

ws_sel   = wb["Selection"]
ws_total = wb["TOTAL"]
sel_rows   = list(ws_sel.iter_rows(min_row=2, values_only=True))
total_rows = list(ws_total.iter_rows(min_row=2, values_only=True))
print(f"  Selection rows: {len(sel_rows)}")
print(f"  TOTAL rows:     {len(total_rows)}")

# Build SDG lookup from TOTAL sheet
# TOTAL cols: 0=GROUP#, 1=PROJECT#, 2-18=SDG1-17, 19=TOTAL, 20=SELECTION
sdg_map = {}
for row in total_rows:
    code = str(row[1]).strip() if row[1] else None
    if not code or code == "None":
        continue
    sdgs = []
    for offset in range(17):
        val = row[2 + offset]
        try:
            if val and float(str(val)) > 0:
                sdgs.append(offset + 1)
        except (ValueError, TypeError):
            pass
    if sdgs:
        sdg_map[code] = sorted(set(sdgs))

print(f"  Projects with SDGs: {len(sdg_map)}")

lines = [
    "-- =============================================================================",
    "-- supabase_import_guidebook_2026.sql",
    "-- Generated by scripts/excel_to_guidebook_sql.py",
    "-- Imports 175 UIA 2026 Guidebook projects (Atlas 3+3 schema)",
    "-- Source: FINAL SELECTION.xlsx",
    "-- =============================================================================",
    "",
    "-- Run AFTER existing supabase_import_projects.sql.",
    "-- Fully idempotent: ON CONFLICT DO NOTHING on all inserts.",
    "",
    "-- ---------------------------------------------------------------------------",
    "-- Step 1: Insert 175 projects",
    "-- ---------------------------------------------------------------------------",
    "",
]

project_codes = []
skipped = 0

for i, row in enumerate(sel_rows, start=1):
    if not row[2]:  # no title = blank/ghost submission, skip entirely
        skipped += 1
        continue

    ext_code = str(row[1]).strip() if row[1] else f"G26_ROW{i}"
    title    = str(row[2]).strip() if row[2] else ext_code
    status   = str(row[4]).strip() if row[4] else ""
    region   = str(row[7]).strip() if row[7] else ""
    location = str(row[8]).strip() if row[8] else ""
    summary  = str(row[6]).strip() if row[6] else "No description provided."
    contact  = str(row[25]).strip() if len(row) > 25 and row[25] else "unknown@unknown.com"
    sel_flag = str(row[26]).strip().upper() if len(row) > 26 and row[26] else ""

    if "," in location:
        idx = location.rfind(",")
        city_raw    = location[:idx].strip()
        country_raw = location[idx+1:].strip()
    else:
        city_raw    = location
        country_raw = "Unknown"

    wf_status  = "'APPROVED'" if sel_flag == "S" else "'SUBMITTED'"
    proj_status = map_status(status)
    region_sql  = map_region(region, country_raw)

    project_codes.append(ext_code)

    lines.append(f"-- Row {i}: {ext_code}")
    lines += [
        "INSERT INTO projects (",
        "    organization_name, contact_person, contact_email, project_name,",
        "    project_status, workflow_status,",
        "    funding_needed, funding_spent,",
        "    uia_region, city, country,",
        "    latitude, longitude,",
        "    brief_description, detailed_description, success_factors,",
        "    gdpr_consent, external_code",
        ") VALUES (",
        f"    'Unknown', 'Unknown', {esc(contact, 255)}, {esc(title, 500)},",
        f"    '{proj_status}', {wf_status},",
        f"    0.0, 0.0,",
        f"    {region_sql}, {esc(city_raw, 255)}, {esc(country_raw, 255)},",
        f"    NULL, NULL,",
        f"    {esc(summary)}, {esc(summary)}, 'See detailed description',",
        f"    TRUE, {esc(ext_code, 16)}",
        ") ON CONFLICT DO NOTHING;",
        "",
    ]

lines += [
    "-- ---------------------------------------------------------------------------",
    "-- Step 2: project_sdgs (SELECT-based insert, keyed on external_code)",
    "-- ---------------------------------------------------------------------------",
    "",
]

sdg_pairs = 0
for code in project_codes:
    for sdg_num in sdg_map.get(code, []):
        lines += [
            "INSERT INTO project_sdgs (project_id, sdg_number)",
            f"SELECT id, {sdg_num} FROM projects WHERE external_code = {esc(code)}",
            "ON CONFLICT DO NOTHING;",
        ]
        sdg_pairs += 1
    if sdg_map.get(code):
        lines.append("")

lines += [
    "-- ---------------------------------------------------------------------------",
    "-- Verification (run after import):",
    "-- ---------------------------------------------------------------------------",
    "-- SELECT COUNT(*) FROM projects;       -- expect 338",
    "-- SELECT COUNT(*) FROM project_sdgs;   -- expect ~1007",
    "-- SELECT workflow_status, COUNT(*) FROM projects",
    "--   WHERE external_code LIKE 'P%' GROUP BY workflow_status;",
    "-- -- expect: APPROVED=68, SUBMITTED=107",
    "",
]

output = "\n".join(lines)
OUTPUT_SQL.write_text(output, encoding="utf-8")
print(f"\nGenerated: {OUTPUT_SQL}")
print(f"  Projects : {len(project_codes)} (skipped {skipped})")
print(f"  SDG rows : {sdg_pairs}")
print(f"  File size: {OUTPUT_SQL.stat().st_size:,} bytes")
print("\nNext: paste supabase_import_guidebook_2026.sql into Supabase SQL Editor")
